# K-Nearest Neighbors
Load the `mnist` dataset. Split it into training and test sets. Train and test a k-nearest neighbor model using scikit-learn. Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [ ]:
import pandas as pd #load data set
import sklearn.model_selection #split the data!!
import sklearn.metrics # to calculate accuracy!!!!
import sklearn.neighbors 
import plotly.express as px

## Loading dataset

In [3]:
df = pd.read_csv('/mnist.csv')
df = df.set_index('id')
df

,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
id,,,,,,,,,,,,,,,,,,,,,
31953,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34452,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60897,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36953,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1981,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25268,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6473,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5821,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1751,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56752,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Spliting Dataset train and test datasets

In [4]:
x = df.drop(['class'], axis=1)
y =df['class']

x_train, x_test, y_train, y_test, = sklearn.model_selection.train_test_split(x,y)

print('df', df.shape)
print('x_train', x_train.shape)
print('x_test', x_test.shape)
print('y_train', y_train.shape)
print('y_test', y_test.shape)

df (4000, 785)
x_train (3000, 784)
x_test (1000, 784)
y_train (3000,)
y_test (1000,)

## Training model

In [5]:
neigh = sklearn.neighbors.KNeighborsClassifier() ## ojo pelao: el parametro mejora el score
neigh.fit(x_train, y_train)

KNeighborsClassifier()

## Testing the trained model

In [6]:
y_predicted = neigh.predict(x_test)
accuracy = sklearn.metrics.accuracy_score(y_test, y_predicted)
accuracy

0.926

## Hyperparameter tuning

In [7]:
k_list = range(1, 10)
metric_list = ['euclidean', 'manhattan', 'chebyshev']
result_df = pd.DataFrame(columns=["K", 'Metric', 'Accuracy'])

for K in k_list:
    for metric in metric_list:
        model = sklearn.neighbors.KNeighborsClassifier(n_neighbors=K, metric=metric)
        model.fit(x_train, y_train)
        y_predicted = model.predict(x_test)
        accuracy = sklearn.metrics.accuracy_score(y_test, y_predicted)
        result_df = result_df.append({'K':K, "Metric": metric, "Accuracy": accuracy}, ignore_index=True)
        
result_df

    K     Metric  Accuracy
0   1  euclidean     0.921
1   1  manhattan     0.909
2   1  chebyshev     0.620
3   2  euclidean     0.890
4   2  manhattan     0.878
5   2  chebyshev     0.551
6   3  euclidean     0.923
7   3  manhattan     0.905
8   3  chebyshev     0.551
9   4  euclidean     0.916
10  4  manhattan     0.901
11  4  chebyshev     0.586
12  5  euclidean     0.926
13  5  manhattan     0.913
14  5  chebyshev     0.585
15  6  euclidean     0.919
16  6  manhattan     0.909
17  6  chebyshev     0.588
18  7  euclidean     0.920
19  7  manhattan     0.905
20  7  chebyshev     0.580
21  8  euclidean     0.925
22  8  manhattan     0.908
23  8  chebyshev     0.576
24  9  euclidean     0.924
25  9  manhattan     0.902
26  9  chebyshev     0.576

## Comparing accuracy in euclidean metric hyperparameter

In [ ]:
k_df = result_df[result_df['Metric']=="euclidean"]

fig = px.line(x=k_df['K'], y=k_df["Accuracy"], labels={'x':'K', 'y':'Accuracy'})
fig.show()